version: "3.9"

services:
  findcare:
    container_name: FindCare
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - findcare-api

  findcare-api:
    container_name: FindCare-API
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --proxy-headers --host 0.0.0.0 --port 8009 --forwarded-allow-ips '*' --log-level debug
    ports:
      - 8009:8009
    depends_on:
      - postgres
    networks:
      - app_net

  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    environment:
      - TZ=Asia/Kolkata
      - POSTGRES_PASSWORD=ryuk
      - POSTGRES_DB=findcare
    expose:
      - 5432
    networks:
      app_net:
        ipv4_address: 192.168.0.2

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ryuk@ryuk.com
      PGADMIN_DEFAULT_PASSWORD: ryuk
      PGADMIN_CONFIG_SERVER_MODE: 'True'
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      app_net:
        ipv4_address: 192.168.0.3
    restart: unless-stopped

networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1
volumes:
  postgres_data:
  pgadmin:
