name: NextCare API

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
 build:
  runs-on: ubuntu-latest
  steps:

    - uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2

    - name: Install python dependencies
      working-directory: backend 
      run: pip install -r requirements.txt
      

    - name: Set context to Okteto Cloud
      uses: okteto/context@latest
      with:
        token: ${{ secrets.OKTETO_TOKEN }}


    - name: Build and deploy application container to Okteto nextcare Namespace
      if: ${{ github.event_name == 'push' }}
      uses: okteto/deploy-stack@master
      with:
        name: nextcare-api
        build: true
